import { StyleSheet } from 'react-native';

export const estate = {
  bg: '#FAF8F5',
  surface: '#FFFFFF',
  border: '#E5E2DC',
  text: '#0F2942',
  sub: '#5C6B7A',
  navy: '#0F2942',
  gold: '#C4A052',
  goldBg: '#F5F0E6',
  accent: '#1A6B4A',
  accentBg: '#E8F5EF',
  warn: '#B45309',
  warnBg: '#FFFBEB',
  danger: '#B91C1C',
  dangerBg: '#FEF2F2',
  radius: 14,
  brandEyebrow: 'The Amantillo Property Co.',
} as const;

export const estateStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: estate.bg },
  flex: { flex: 1 },
  scroll: { paddingBottom: 28 },
  scrollPadded: { paddingHorizontal: 16, paddingTop: 8, paddingBottom: 28 },

  hero: {
    marginHorizontal: 16,
    marginTop: 8,
    backgroundColor: estate.navy,
    borderRadius: estate.radius,
    padding: 20,
    overflow: 'hidden',
  },
  heroEyebrow: {
    fontSize: 11,
    fontWeight: '700',
    color: estate.gold,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  heroTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#fff',
    marginTop: 8,
    lineHeight: 28,
  },
  heroSubtitle: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.78)',
    lineHeight: 19,
    marginTop: 8,
  },

  statsRow: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 16,
    marginTop: 16,
  },
  statsColumn: {
    flexDirection: 'column',
    gap: 10,
    paddingHorizontal: 16,
    marginTop: 16,
  },
  statChip: {
    flex: 1,
    backgroundColor: estate.surface,
    borderRadius: estate.radius,
    borderWidth: 1,
    borderColor: estate.border,
    paddingVertical: 14,
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  statChipStacked: {
    flex: 0,
    alignSelf: 'stretch',
  },
  statValue: { fontSize: 20, fontWeight: '800', color: estate.navy },
  statLabel: {
    fontSize: 11,
    color: estate.sub,
    marginTop: 4,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },

  warnBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: estate.warnBg,
    borderWidth: 1,
    borderColor: '#FCD34D',
    borderRadius: estate.radius,
    padding: 12,
    marginHorizontal: 16,
    marginTop: 16,
  },
  warnIcon: { fontSize: 14, color: estate.warn, marginTop: 1 },
  warnText: { flex: 1, fontSize: 13, color: '#92400E', lineHeight: 18 },

  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginTop: 28,
    marginBottom: 12,
  },
  sectionHeaderLeft: { flex: 1, marginRight: 12 },
  sectionTitle: { fontSize: 18, fontWeight: '800', color: estate.text },
  sectionSubtitle: { fontSize: 12, color: estate.sub, marginTop: 4 },
  sectionAction: { fontSize: 13, fontWeight: '700', color: estate.gold },

  card: {
    marginHorizontal: 16,
    backgroundColor: estate.surface,
    borderRadius: estate.radius,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: estate.border,
    shadowColor: estate.navy,
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  cardTitle: { fontSize: 17, fontWeight: '800', color: estate.text },
  cardMeta: { fontSize: 13, color: estate.sub, marginTop: 6 },
  cardAmount: {
    fontSize: 20,
    fontWeight: '800',
    color: estate.navy,
    marginTop: 10,
  },

  badge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  badgePaid: { backgroundColor: estate.accentBg },
  badgeUnpaid: { backgroundColor: estate.warnBg },
  badgeText: { fontSize: 10, fontWeight: '800', letterSpacing: 0.4 },
  badgeTextPaid: { color: estate.accent },
  badgeTextUnpaid: { color: estate.warn },

  empty: {
    marginHorizontal: 16,
    backgroundColor: estate.surface,
    borderRadius: estate.radius,
    borderWidth: 1,
    borderColor: estate.border,
    paddingVertical: 32,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  emptyIcon: { fontSize: 32, marginBottom: 8 },
  emptyTitle: { fontSize: 15, fontWeight: '700', color: estate.text },
  emptyText: {
    fontSize: 13,
    color: estate.sub,
    textAlign: 'center',
    marginTop: 6,
    lineHeight: 18,
  },

  highlight: {
    flexDirection: 'row',
    marginTop: 18,
    backgroundColor: estate.goldBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E8DFC8',
    overflow: 'hidden',
  },
  highlightBlock: { flex: 1, padding: 16, alignItems: 'center' },
  highlightDivider: {
    width: StyleSheet.hairlineWidth,
    backgroundColor: estate.border,
  },
  highlightLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: estate.sub,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  highlightValue: {
    fontSize: 18,
    fontWeight: '800',
    color: estate.navy,
    marginTop: 6,
  },

  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  detailLabel: { fontSize: 14, color: estate.sub },
  detailValue: { fontSize: 14, fontWeight: '700', color: estate.text },
  detailsBlock: {
    marginTop: 18,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: estate.border,
    gap: 10,
  },

  rowCard: {
    marginHorizontal: 16,
    backgroundColor: estate.surface,
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: estate.border,
  },
  rowTitle: { fontSize: 15, fontWeight: '700', color: estate.text },
  rowMeta: { fontSize: 13, color: estate.sub, marginTop: 4 },

  primaryBtn: {
    backgroundColor: estate.navy,
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 12,
  },
  primaryBtnDisabled: { opacity: 0.7 },
  primaryBtnText: { color: '#fff', fontWeight: '700', fontSize: 16 },

  menuItem: {
    marginHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: estate.surface,
    padding: 16,
    borderRadius: estate.radius,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: estate.border,
  },
  menuText: { fontSize: 16, fontWeight: '700', color: estate.text },
  menuChevron: { fontSize: 22, color: estate.gold, fontWeight: '600' },

  footer: { marginTop: 24, paddingHorizontal: 24, alignItems: 'center' },
  footerText: {
    fontSize: 11,
    color: estate.sub,
    textAlign: 'center',
    lineHeight: 16,
  },
});
