export default {
  LOGIN: 'Login',
  REGISTER: 'Register',
  STAFF_BLOCKED: 'StaffBlocked',
  MAIN_TABS: 'MainTabs',
  DASHBOARD: 'Dashboard',
  HOME: 'Dashboard',
  CATALOG: 'Catalog',
  TRANSACTIONS: 'Transactions',
  ADMIN_NOTIFICATIONS: 'AdminNotifications',
  ACTIVITY_LOGS: 'ActivityLogs',
  DATA_RECORDS: 'DataRecords',
  CHECKOUT: 'Checkout',
  PAYMENT: 'Payment',
  MY_TRANSACTIONS: 'MyTransactions',
  PROFILE: 'Profile',
  LANDING: 'Landing',
} as const;
